[package]
edition = "2024"
name = "javy-plugin-kubewarden"
version = "0.2.0"

[lib]
crate-type = ["cdylib"]
name = "javy_plugin_kubewarden"

[dependencies]
javy-plugin-api = "5.0"
wit-bindgen = "0.48"
